version: "3.7"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: rent-a-car
      PGDATA: /var/lib/postgresql/data
    ports:
      - '5432:5432'
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    restart: always

  s-pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: postgresMail@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres1234
    ports:
      - '5050:80'

volumes:
  postgres-volume:



